# Generated by Django 4.0.6 on 2022-08-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
